"""recreate tables

Revision ID: 3c23e2352300
Revises: b54f0f6d0e71
Create Date: 2023-07-17 17:11:25.805047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c23e2352300'
down_revision = 'b54f0f6d0e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_public_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_name'), type_='unique')
        batch_op.create_unique_constraint('uq_users_public_id', ['public_id'])

    # ### end Alembic commands ###
